#Spring Connfig Server Conf   
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/m0nnyka/alphashop-ms
          username: m0nnyka #${github.username}
          password: f*l #${github.password}
          cloneOnStart: true
          searchPaths: promoartservice
  application:
    name: config-server
   
      
      
     