#Spring Connfig Server Conf  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/nicola/Documents/git-config
          #uri: file:///home/nicola/Documents/git-config-repository
   
      
      
     